// ============================================================
// PDF Report Generator
// Print-based (Save as PDF) for lightweight academic reports
// html2canvas + jsPDF for direct download option
// ============================================================

import type { AnalysisResults, AIResults } from "@/types";
import { getSummaryAPA } from "@/lib/analysis/registry";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

function buildReportHTML(
  results: AnalysisResults,
  aiResults: AIResults | null,
  researchGoal: string
): string {
  const { reliability, validity, efa, stability, meta } = results;

  const alphaLabel =
    reliability.cronbachsAlpha >= 0.9 ? "Excellent" :
    reliability.cronbachsAlpha >= 0.8 ? "Good" :
    reliability.cronbachsAlpha >= 0.7 ? "Acceptable" : "Low";

  const kmoLabel =
    validity.kmo >= 0.9 ? "Marvelous" :
    validity.kmo >= 0.8 ? "Meritorious" :
    validity.kmo >= 0.7 ? "Middling" :
    validity.kmo >= 0.6 ? "Mediocre" : "Unacceptable";

  const stabilityEmoji =
    stability.stabilityLevel === "stable" ? "Stable" :
    stability.stabilityLevel === "moderate" ? "Moderate" : "Unstable";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Reliability & Validity Analysis Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', serif; font-size: 11pt; line-height: 1.6; color: #1a1a1a; max-width: 700px; margin: 40px auto; padding: 20px; }
  h1 { font-size: 18pt; font-weight: 700; margin-bottom: 4px; letter-spacing: -0.5px; }
  h2 { font-size: 13pt; font-weight: 600; margin: 24px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #e5e7eb; }
  h3 { font-size: 11pt; font-weight: 600; margin: 12px 0 4px; }
  .meta { color: #6b7280; font-size: 9pt; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; font-size: 9pt; }
  th, td { padding: 4px 8px; text-align: left; border-bottom: 1px solid #f3f4f6; }
  th { font-weight: 600; color: #6b7280; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.5px; }
  .stat { font-weight: 600; }
  .good { color: #059669; }
  .warn { color: #d97706; }
  .bad { color: #dc2626; }
  pre { background: #f9fafb; padding: 12px; border-radius: 6px; font-size: 9pt; white-space: pre-wrap; border: 1px solid #e5e7eb; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 8pt; color: #9ca3af; }
  @media print { body { margin: 0; padding: 0.5in; } h2 { break-after: avoid; } table { break-inside: avoid; } }
</style>
</head>
<body>
<h1>Scale Reliability &amp; Validity Analysis Report</h1>
<p class="meta">Generated by AI Reliability &amp; Validity Analyzer — ${new Date(meta.timestamp).toISOString().slice(0, 10)}</p>
${researchGoal ? `<p class="meta">Research Goal: ${escapeHtml(researchGoal)}</p>` : ""}

<h2>1. Sample Overview</h2>
<table>
  <tr><td>Sample Size (N)</td><td class="stat">${meta.sampleSize}</td></tr>
  <tr><td>Number of Items</td><td class="stat">${meta.itemCount}</td></tr>
  <tr><td>Analysis Duration</td><td class="stat">${(meta.analysisDurationMs / 1000).toFixed(1)}s</td></tr>
</table>

<h2>2. Reliability Analysis</h2>
<table>
  <tr><td>Cronbach's &alpha;</td><td class="stat">${reliability.cronbachsAlpha.toFixed(3)} <span class="${reliability.cronbachsAlpha >= 0.8 ? 'good' : reliability.cronbachsAlpha >= 0.7 ? 'warn' : 'bad'}">(${alphaLabel})</span></td></tr>
  <tr><td>Standardized &alpha;</td><td class="stat">${reliability.standardizedAlpha.toFixed(3)}</td></tr>
</table>

<h3>Item-Total Correlations</h3>
<table>
  <tr><th>Item</th><th>Corrected Item-Total r</th><th>&alpha; if Deleted</th></tr>
  ${Object.entries(reliability.itemTotalCorrelation).slice(0, 30).map(([item, corr]) => `
  <tr>
    <td>${escapeHtml(item)}</td>
    <td class="stat ${corr < 0.3 ? 'bad' : corr < 0.4 ? 'warn' : 'good'}">${corr.toFixed(3)}</td>
    <td class="stat">${reliability.alphaIfItemDeleted[item]?.toFixed(3) ?? "-"}</td>
  </tr>`).join("")}
</table>

<h2>3. Validity Analysis</h2>
<table>
  <tr><td>KMO Measure</td><td class="stat">${validity.kmo.toFixed(3)} <span class="${validity.kmo >= 0.8 ? 'good' : validity.kmo >= 0.6 ? 'warn' : 'bad'}">(${kmoLabel})</span></td></tr>
  <tr><td>Bartlett's &chi;&sup2;</td><td class="stat">${validity.bartlettChiSquare.toFixed(2)}</td></tr>
  <tr><td>Bartlett's df</td><td class="stat">${validity.bartlettDf}</td></tr>
  <tr><td>Bartlett's p</td><td class="stat">${validity.bartlettPValue < 0.001 ? "&lt; .001" : validity.bartlettPValue.toFixed(3)}</td></tr>
</table>

<h2>4. Exploratory Factor Analysis</h2>
<table>
  <tr><td>Suggested Factors</td><td class="stat">${efa.suggestedFactors}</td></tr>
  <tr><td>Rotation Method</td><td class="stat">${efa.rotation}</td></tr>
  <tr><td>Total Variance Explained</td><td class="stat">${(efa.varianceExplained.reduce((a, b) => a + b, 0) * 100).toFixed(1)}%</td></tr>
</table>

<h3>Factor Loadings</h3>
<table>
  <tr>
    <th>Item</th>
    ${Array.from({length: efa.suggestedFactors}, (_, i) => `<th>F${i + 1}</th>`).join("")}
    <th>Communality</th>
  </tr>
  ${efa.loadings.slice(0, 30).map((row, i) => `
  <tr>
    <td>${escapeHtml(efa.itemLabels[i] ?? `Q${i + 1}`)}</td>
    ${row.slice(0, efa.suggestedFactors).map(l => `<td class="stat">${l.toFixed(3)}</td>`).join("")}
    <td class="stat">${efa.communalities[i]?.toFixed(3) ?? "-"}</td>
  </tr>`).join("")}
</table>

<h2>5. Sample Stability</h2>
<table>
  <tr><td>Stability Level</td><td class="stat ${stability.stabilityLevel === 'stable' ? 'good' : stability.stabilityLevel === 'moderate' ? 'warn' : 'bad'}">${stabilityEmoji}</td></tr>
  <tr><td>Recommended N</td><td class="stat">${stability.recommendedSampleSize}</td></tr>
  ${stability.elbowPoint ? `<tr><td>Elbow Point</td><td class="stat">n = ${stability.elbowPoint}</td></tr>` : ""}
  <tr><td>Bootstrap Samples</td><td class="stat">${stability.bootstrapSamples}</td></tr>
</table>

${aiResults ? `
<h2>6. APA Summary</h2>
<pre>${escapeHtml(getSummaryAPA(results))}</pre>

<h2>7. AI Interpretation</h2>
<h3>Plain-Language Summary</h3>
<p>${escapeHtml(aiResults.explanation.simple)}</p>
<h3>Academic Interpretation</h3>
<p>${escapeHtml(aiResults.explanation.academic)}</p>
${aiResults.suggestions.length > 0 ? `<h3>Advisor Suggestions</h3>${aiResults.suggestions.map(s => `<p><strong>[${s.severity}]</strong> ${escapeHtml(s.title)}: ${escapeHtml(s.detail)}</p>`).join("")}` : ""}
<h3>APA-Formatted Results</h3>
<pre>${escapeHtml(aiResults.apaResult)}</pre>
` : ""}

<h2>8. Method Recommendation</h2>
<p>${escapeHtml(results.recommendedMethod)}</p>

<div class="footer">Report generated by AI Reliability &amp; Validity Analyzer v1.0.0 — All analyses performed locally in the browser.</div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/**
 * Generate and download a PDF report using browser print API.
 * Opens the print dialog (Save as PDF).
 */
export function printPDF(
  results: AnalysisResults,
  aiResults: AIResults | null,
  researchGoal: string
): void {
  const html = buildReportHTML(results, aiResults, researchGoal);

  const printWindow = window.open("", "_blank", "width=800,height=600");
  if (!printWindow) {
    alert("Please allow pop-ups to export PDF");
    return;
  }

  const doc = printWindow.document;
  doc.open();
  doc.write(html);
  doc.close();

  printWindow.addEventListener("load", () => {
    setTimeout(() => printWindow.print(), 300);
  }, { once: true });
}

/**
 * Generate PDF as downloadable blob (html2canvas + jsPDF).
 * Direct download without print dialog. Heavier but more convenient.
 */
export async function downloadPDF(
  elementId: string,
  filename = "analysis-report.pdf"
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) throw new Error("Report element not found");

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#FAFAF9",
  });

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const imgWidth = pageWidth - 20;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let heightLeft = imgHeight;
  let position = 10;

  pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
  heightLeft -= pageHeight - 20;

  while (heightLeft > 0) {
    position = heightLeft - imgHeight + 10;
    pdf.addPage();
    pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - 20;
  }

  pdf.save(filename);
}
