// ============================================================
// PDF Report Generator — Fully bilingual (zh / en)
// Print-based (Save as PDF) for lightweight academic reports
// ============================================================

import type { AnalysisResults, AIResults } from "@/types";
import { getSummaryAPA } from "@/lib/analysis/registry";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

type Lang = "zh" | "en";

const T: Record<string, Record<Lang, string>> = {
  title: { zh: "SurveyLens 分析报告", en: "SurveyLens Analysis Report" },
  generated: { zh: "由 SurveyLens 生成", en: "Generated by SurveyLens" },
  researchGoal: { zh: "研究目标", en: "Research Goal" },
  sampleOverview: { zh: "1. 样本概览", en: "1. Sample Overview" },
  sampleSize: { zh: "样本量 (N)", en: "Sample Size (N)" },
  itemCount: { zh: "题项数量", en: "Number of Items" },
  analysisDuration: { zh: "分析用时", en: "Analysis Duration" },
  reliability: { zh: "2. 信度分析", en: "2. Reliability Analysis" },
  cronbachsAlpha: { zh: "Cronbach's α", en: "Cronbach's α" },
  standardizedAlpha: { zh: "标准化 α", en: "Standardized α" },
  itemTotal: { zh: "题总相关", en: "Item-Total Correlations" },
  item: { zh: "题项", en: "Item" },
  correctedItemTotal: { zh: "校正题总相关 r", en: "Corrected Item-Total r" },
  alphaIfDeleted: { zh: "删除后 α", en: "α if Deleted" },
  validity: { zh: "3. 效度分析", en: "3. Validity Analysis" },
  kmo: { zh: "KMO 值", en: "KMO Measure" },
  bartlettChi: { zh: "Bartlett χ²", en: "Bartlett's χ²" },
  bartlettDf: { zh: "Bartlett df", en: "Bartlett's df" },
  bartlettP: { zh: "Bartlett p", en: "Bartlett's p" },
  efa: { zh: "4. 探索性因子分析", en: "4. Exploratory Factor Analysis" },
  suggestedFactors: { zh: "建议因子数", en: "Suggested Factors" },
  rotationMethod: { zh: "旋转方法", en: "Rotation Method" },
  varianceExplained: { zh: "累计方差解释率", en: "Total Variance Explained" },
  factorLoadings: { zh: "因子载荷", en: "Factor Loadings" },
  communality: { zh: "共同度", en: "Communality" },
  stability: { zh: "5. 样本稳定性", en: "5. Sample Stability" },
  stabilityLevel: { zh: "稳定性水平", en: "Stability Level" },
  recommendedN: { zh: "建议样本量", en: "Recommended N" },
  elbowPoint: { zh: "拐点", en: "Elbow Point" },
  bootstrapSamples: { zh: "Bootstrap 样本数", en: "Bootstrap Samples" },
  apaSummary: { zh: "6. APA 摘要", en: "6. APA Summary" },
  aiInterpretation: { zh: "7. AI 解读", en: "7. AI Interpretation" },
  plainSummary: { zh: "通俗解读", en: "Plain-Language Summary" },
  academicInterpretation: { zh: "学术解读", en: "Academic Interpretation" },
  advisorSuggestions: { zh: "诊断建议", en: "Advisor Suggestions" },
  apaResults: { zh: "APA 格式结果", en: "APA-Formatted Results" },
  methodRecommendation: { zh: "8. 方法建议", en: "8. Method Recommendation" },
  footer: { zh: "报告由 SurveyLens v1.0.0 生成 — 所有分析均在浏览器本地完成", en: "Report generated by SurveyLens v1.0.0 — All analyses performed locally in the browser." },
  createdAt: { zh: "生成日期", en: "Generated" },
  seconds: { zh: "秒", en: "s" },
};

function alphaLabel(v: number, lang: Lang): string {
  if (lang === "zh") {
    return v >= 0.9 ? "优秀" : v >= 0.8 ? "良好" : v >= 0.7 ? "可接受" : "偏低";
  }
  return v >= 0.9 ? "Excellent" : v >= 0.8 ? "Good" : v >= 0.7 ? "Acceptable" : "Low";
}

function kmoLabel(v: number, lang: Lang): string {
  if (lang === "zh") {
    return v >= 0.9 ? "极佳" : v >= 0.8 ? "良好" : v >= 0.7 ? "中等" : v >= 0.6 ? "一般" : "不可接受";
  }
  return v >= 0.9 ? "Marvelous" : v >= 0.8 ? "Meritorious" : v >= 0.7 ? "Middling" : v >= 0.6 ? "Mediocre" : "Unacceptable";
}

function stabilityLabel(level: string, lang: Lang): string {
  if (lang === "zh") return level === "stable" ? "稳定" : level === "moderate" ? "中等" : "不稳定";
  return level === "stable" ? "Stable" : level === "moderate" ? "Moderate" : "Unstable";
}

function buildReportHTML(
  results: AnalysisResults,
  aiResults: AIResults | null,
  researchGoal: string,
  lang: Lang = "zh"
): string {
  const { reliability, validity, efa, stability, meta } = results;
  const t = (key: string) => T[key]?.[lang] ?? key;

  return `<!DOCTYPE html>
<html lang="${lang === "zh" ? "zh-CN" : "en"}">
<head>
<meta charset="UTF-8">
<title>${t("title")}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', 'Noto Sans SC', serif; font-size: 11pt; line-height: 1.6; color: #1a1a1a; max-width: 700px; margin: 40px auto; padding: 20px; }
  h1 { font-size: 18pt; font-weight: 700; margin-bottom: 4px; letter-spacing: -0.5px; }
  h2 { font-size: 13pt; font-weight: 600; margin: 24px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #e5e7eb; }
  h3 { font-size: 11pt; font-weight: 600; margin: 12px 0 4px; }
  .meta { color: #6b7280; font-size: 9pt; margin-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; font-size: 9pt; }
  th, td { padding: 4px 8px; text-align: left; border-bottom: 1px solid #f3f4f6; }
  th { font-weight: 600; color: #6b7280; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.5px; }
  .stat { font-weight: 600; }
  .good { color: #059669; }
  .warn { color: #d97706; }
  .bad { color: #dc2626; }
  pre { background: #f9fafb; padding: 12px; border-radius: 6px; font-size: 9pt; white-space: pre-wrap; border: 1px solid #e5e7eb; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 8pt; color: #9ca3af; }
  @media print { body { margin: 0; padding: 0.5in; } h2 { break-after: avoid; } table { break-inside: avoid; } }
</style>
</head>
<body>
<h1>${t("title")}</h1>
<p class="meta">${t("generated")} — ${new Date(meta.timestamp).toISOString().slice(0, 10)}</p>
${researchGoal ? `<p class="meta">${t("researchGoal")}: ${escapeHtml(researchGoal)}</p>` : ""}

<h2>${t("sampleOverview")}</h2>
<table>
  <tr><td>${t("sampleSize")}</td><td class="stat">${meta.sampleSize}</td></tr>
  <tr><td>${t("itemCount")}</td><td class="stat">${meta.itemCount}</td></tr>
  <tr><td>${t("analysisDuration")}</td><td class="stat">${(meta.analysisDurationMs / 1000).toFixed(1)}${t("seconds")}</td></tr>
</table>

<h2>${t("reliability")}</h2>
<table>
  <tr><td>${t("cronbachsAlpha")}</td><td class="stat">${reliability.cronbachsAlpha.toFixed(3)} <span class="${reliability.cronbachsAlpha >= 0.8 ? 'good' : reliability.cronbachsAlpha >= 0.7 ? 'warn' : 'bad'}">(${alphaLabel(reliability.cronbachsAlpha, lang)})</span></td></tr>
  <tr><td>${t("standardizedAlpha")}</td><td class="stat">${reliability.standardizedAlpha.toFixed(3)}</td></tr>
</table>

<h3>${t("itemTotal")}</h3>
<table>
  <tr><th>${t("item")}</th><th>${t("correctedItemTotal")}</th><th>${t("alphaIfDeleted")}</th></tr>
  ${Object.entries(reliability.itemTotalCorrelation).slice(0, 30).map(([item, corr]) => `
  <tr>
    <td>${escapeHtml(item)}</td>
    <td class="stat ${corr < 0.3 ? 'bad' : corr < 0.4 ? 'warn' : 'good'}">${corr.toFixed(3)}</td>
    <td class="stat">${reliability.alphaIfItemDeleted[item]?.toFixed(3) ?? "-"}</td>
  </tr>`).join("")}
</table>

<h2>${t("validity")}</h2>
<table>
  <tr><td>${t("kmo")}</td><td class="stat">${validity.kmo.toFixed(3)} <span class="${validity.kmo >= 0.8 ? 'good' : validity.kmo >= 0.6 ? 'warn' : 'bad'}">(${kmoLabel(validity.kmo, lang)})</span></td></tr>
  <tr><td>${t("bartlettChi")}</td><td class="stat">${validity.bartlettChiSquare.toFixed(2)}</td></tr>
  <tr><td>${t("bartlettDf")}</td><td class="stat">${validity.bartlettDf}</td></tr>
  <tr><td>${t("bartlettP")}</td><td class="stat">${validity.bartlettPValue < 0.001 ? "&lt; .001" : validity.bartlettPValue.toFixed(3)}</td></tr>
</table>

<h2>${t("efa")}</h2>
<table>
  <tr><td>${t("suggestedFactors")}</td><td class="stat">${efa.suggestedFactors}</td></tr>
  <tr><td>${t("rotationMethod")}</td><td class="stat">${efa.rotation}</td></tr>
  <tr><td>${t("varianceExplained")}</td><td class="stat">${(efa.varianceExplained.reduce((a, b) => a + b, 0) * 100).toFixed(1)}%</td></tr>
</table>

<h3>${t("factorLoadings")}</h3>
<table>
  <tr>
    <th>${t("item")}</th>
    ${Array.from({length: efa.suggestedFactors}, (_, i) => `<th>F${i + 1}</th>`).join("")}
    <th>${t("communality")}</th>
  </tr>
  ${efa.loadings.slice(0, 30).map((row, i) => `
  <tr>
    <td>${escapeHtml(efa.itemLabels[i] ?? `Q${i + 1}`)}</td>
    ${row.slice(0, efa.suggestedFactors).map(l => `<td class="stat">${l.toFixed(3)}</td>`).join("")}
    <td class="stat">${efa.communalities[i]?.toFixed(3) ?? "-"}</td>
  </tr>`).join("")}
</table>

<h2>${t("stability")}</h2>
<table>
  <tr><td>${t("stabilityLevel")}</td><td class="stat ${stability.stabilityLevel === 'stable' ? 'good' : stability.stabilityLevel === 'moderate' ? 'warn' : 'bad'}">${stabilityLabel(stability.stabilityLevel, lang)}</td></tr>
  <tr><td>${t("recommendedN")}</td><td class="stat">${stability.recommendedSampleSize}</td></tr>
  ${stability.elbowPoint ? `<tr><td>${t("elbowPoint")}</td><td class="stat">n = ${stability.elbowPoint}</td></tr>` : ""}
  <tr><td>${t("bootstrapSamples")}</td><td class="stat">${stability.bootstrapSamples}</td></tr>
</table>

<h2>${t("apaSummary")}</h2>
<p>${escapeHtml(getSummaryAPA(results, lang))}</p>

${aiResults ? `
<h2>${t("aiInterpretation")}</h2>
<h3>${t("plainSummary")}</h3>
<p>${escapeHtml(aiResults.explanation.simple)}</p>
<h3>${t("academicInterpretation")}</h3>
<p>${escapeHtml(aiResults.explanation.academic)}</p>
${aiResults.suggestions.length > 0 ? `<h3>${t("advisorSuggestions")}</h3>${aiResults.suggestions.map(s => `<p><strong>[${s.severity}]</strong> ${escapeHtml(s.title)}: ${escapeHtml(s.detail)}</p>`).join("")}` : ""}
<h3>${t("apaResults")}</h3>
<pre>${escapeHtml(aiResults.apaResult)}</pre>
` : ""}

<h2>${t("methodRecommendation")}</h2>
<p>${escapeHtml(results.recommendedMethod)}</p>

<div class="footer">${t("footer")}</div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function printPDF(
  results: AnalysisResults,
  aiResults: AIResults | null,
  researchGoal: string,
  lang: Lang = "zh"
): void {
  const html = buildReportHTML(results, aiResults, researchGoal, lang);

  const printWindow = window.open("", "_blank", "width=800,height=600");
  if (!printWindow) {
    alert(lang === "zh" ? "请允许弹窗以导出 PDF" : "Please allow pop-ups to export PDF");
    return;
  }

  const doc = printWindow.document;
  doc.open();
  doc.write(html);
  doc.close();

  printWindow.addEventListener("load", () => {
    setTimeout(() => printWindow.print(), 300);
  }, { once: true });
}

export async function downloadPDF(
  elementId: string,
  filename = "analysis-report.pdf"
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) throw new Error("Report element not found");

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#FAFAF9",
  });

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF("p", "mm", "a4");
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const imgWidth = pageWidth - 20;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let heightLeft = imgHeight;
  let position = 10;

  pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
  heightLeft -= pageHeight - 20;

  while (heightLeft > 0) {
    position = heightLeft - imgHeight + 10;
    pdf.addPage();
    pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - 20;
  }

  pdf.save(filename);
}
